# Change these first
owner: quickcode-ai # Your GitHub organization or username, where this repository lives
repo: quickcode-status # The name of this repository

sites:
  - name: Quickcode Homepage
    url: https://quickcode.ai
  - name: Quickcode Product
    url: https://qc.quickcode.ai
  - name: Test Broken Site to see if Quickcode/Slack integration is working
    url: https://thissitedoesnotexist.koj.co

assignees:
  - quickcode-ai/devs

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /quickcode-status
  favicon: https://qc.quickcode.ai/favicon.ico
  # logoUrl: https://qc.quickcode.ai/assets/images/logo-color.png
  logoUrl: https://qc.quickcode.ai/assets/images/logo-square.png
  name: Quickcode Status
  introTitle: "**Quickcode:** Machine learning automation for unstructured text, empowering human experts"
  introMessage: This page monitors the availability and health of Quickcode services.
  theme: ocean
  navbar:
    - title: Status
      href: /quickcode-status
    - title: Quickcode
      href: https://quickcode.ai
    - title: Sign In
      href: https://qc.quickcode.ai

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration