# Change these first
owner: quickcode-ai # Your GitHub organization or username, where this repository lives
repo: quickcode-status # The name of this repository

sites:
  - name: Quickcode Homepage
    slug: quickcode-homepage
    url: https://quickcod.ai
  - name: Quickcode
    slug: quickcode-product
    url: https://hs.quickcode.ai
  - name: Quickcode Auth
    slug: quickcode-auth
    url: https://hs.quickcode.ai/auth/
  - name: QCTC
    slug: qctc-product
    url: https://qc.quickcode.ai
  - name: QCTC Auth
    slug: qctc-auth
    url: https://qc.quickcode.ai/auth/
  # - name: Quickcode API
  #   slug: quickcode-api
  #   url: https://qc.quickcode.ai/api/v2/version
  # - name: Quickcode Services
  #   slug: quickcode-services
  #   url: https://qc.quickcode.ai/health

assignees:
  - ross-nordstrom
  - jmorales4
  - quickcode-ai/devs

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /quickcode-status
  favicon: https://hs.quickcode.ai/favicon.ico
  # logoUrl: https://qc.quickcode.ai/assets/images/logo-color.png
  logoUrl: https://hs.quickcode.ai/assets/images/logos/logo-square.png
  name: Quickcode Status
  introTitle: "**Quickcode:** HS Classification Simplified"
  introMessage: This page monitors the availability and health of Quickcode services.
  theme: light
  navbar:
    - title: Status
      href: /quickcode-status
    - title: Quickcode
      href: https://quickcode.ai
    - title: Sign In
      href: https://hs.quickcode.ai

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
